---
name: Black
description: Auto Lint Python code with Black
author: ixxeL
inputs:
  working-dir:
    description: directory in which to find the Dockerfile
    required: false
    default: .

runs:
  using: composite
  steps:
  - id: flake8
    run: |
      echo -e "${BLUE}[ STEP - AUTO-LINTING CODE ] > Linting Python code with Black.${BLANK}"
      echo -e "${CYAN}[ INFO ] > Black version.${BLANK}"
      black --version
      echo -e "${YELLOW}[ EXECUTING ] > Executing Python code auto-linting in ${{ inputs.working-dir }} directory.${BLANK}"
      echo -e "${CYAN}[ INFO ] > Black linting result.${BLANK}"
      black --color --diff ${{ inputs.working-dir }}
      echo -e "${CYAN}[ INFO ] > Processing Black linting...${BLANK}"
      black -v ${{ inputs.working-dir }}
    shell: bash
    env:
      RED: \033[1;31m
      GREEN: \033[1;32m
      YELLOW: \033[1;33m
      BLUE: \033[1;34m
      PURPLE: \033[1;35m
      CYAN: \033[1;36m
      BLANK: \033[0m
